version: '3.3'

services:
  # Banco de Dados para o Serviço de Autenticação
  postgres-db:
    image: postgres:15
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Banco de Dados para o Serviço de Produtos
  mongo-db:
    image: mongo:latest
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: